use_frameworks!

platform :ios, '8.0'

target 'XVIEWNetWorkManager_Example' do
  pod 'XVIEWNetWorkManager', :path => '../'

  target 'XVIEWNetWorkManager_Tests' do
    inherit! :search_paths

    
  end
end
